/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomas_lapa;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
/**
 *
 * @author Emīls
 */
public class nomas_lapa extends javax.swing.JFrame {

    /**
     *
     */
    public double noma;

    /**
     *
     */
    public double pacelajs;

    /**
     *
     */
    public double summa_ar_pvn;
    public int rekins = 0;
    public String rezultats = "";
    public String laiks = "";
    public String pacelshana = "";
    /**
     *
     * @return
     */
    public double getAmount()
    {
        summa_ar_pvn = pacelajs + noma;
        return summa_ar_pvn;
    }
    /**
     * Creates new form nomas_lapa
     */
    public nomas_lapa() {
        initComponents();
        setExtendedState(frame2.MAXIMIZED_BOTH);
        this.setTitle("Noma");
    }
    javax.swing.JFrame frame2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noma_grupa = new javax.swing.ButtonGroup();
        pacelajs_grupa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jText_talrunis = new javax.swing.JTextField();
        jText_adrese = new javax.swing.JTextField();
        jText_epasts = new javax.swing.JTextField();
        jText_vards = new javax.swing.JTextField();
        jText_uzvards = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_iziet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText_ceks = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadio_slepjukomplekts = new javax.swing.JRadioButton();
        jRadio_slepes = new javax.swing.JRadioButton();
        jRadio_nujas = new javax.swing.JRadioButton();
        jRadio_slepjukivere = new javax.swing.JRadioButton();
        jRadio_slepjuzabaki = new javax.swing.JRadioButton();
        jText_slepes_garums = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jText_slepes_zabaki = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jText_sum_bez_pvn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jText_summa = new javax.swing.JTextField();
        jText_pvn = new javax.swing.JTextField();
        jButton_dzest = new javax.swing.JButton();
        jButton_aprekinat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jRadio_noma1 = new javax.swing.JRadioButton();
        jRadio_noma2 = new javax.swing.JRadioButton();
        jRadio_noma4 = new javax.swing.JRadioButton();
        jRadio_nomadiena = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jRadio_pacelajs1 = new javax.swing.JRadioButton();
        jRadio_pacelajs2 = new javax.swing.JRadioButton();
        jRadio_pacelajs4 = new javax.swing.JRadioButton();
        jRadio_pacelajsdiena = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jRadio_snovakomplekts = new javax.swing.JRadioButton();
        jRadio_delis = new javax.swing.JRadioButton();
        jRadio_snovakivere = new javax.swing.JRadioButton();
        jRadio_snovazabaki = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jText_delis_garums = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jText_snova_zabaki = new javax.swing.JTextField();
        jTime = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jRekinanr = new javax.swing.JLabel();
        jButton_notiritcheku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(185, 185, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 85)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 196));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nomas reģistrācijas lapa");

        jPanel2.setBackground(new java.awt.Color(185, 185, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Uzvārds:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Vārds:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Tālrunis:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Adrese:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 27)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("E-pasts:");

        jText_talrunis.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jText_talrunis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_talrunis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_talrunis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_talrunisActionPerformed(evt);
            }
        });

        jText_adrese.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jText_adrese.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_adrese.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_adrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_adreseActionPerformed(evt);
            }
        });

        jText_epasts.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jText_epasts.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_epasts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_epasts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_epastsActionPerformed(evt);
            }
        });

        jText_vards.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jText_vards.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_vards.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_vards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_vardsActionPerformed(evt);
            }
        });

        jText_uzvards.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jText_uzvards.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_uzvards.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_uzvards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_uzvardsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jText_epasts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText_adrese, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText_talrunis, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText_vards, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jText_uzvards, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jText_vards, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jText_uzvards, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jText_talrunis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jText_adrese, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jText_epasts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Čeks:");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(73, 73, 73));
        jButton1.setText("Izdrukāt");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_iziet.setBackground(new java.awt.Color(255, 51, 0));
        jButton_iziet.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jButton_iziet.setForeground(new java.awt.Color(73, 73, 73));
        jButton_iziet.setText("Iziet");
        jButton_iziet.setBorder(null);
        jButton_iziet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_izietActionPerformed(evt);
            }
        });

        jText_ceks.setEditable(false);
        jText_ceks.setColumns(20);
        jText_ceks.setRows(5);
        jText_ceks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jScrollPane1.setViewportView(jText_ceks);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Inventārs:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Info:");

        jPanel3.setBackground(new java.awt.Color(185, 185, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(609, 207));

        jRadio_slepjukomplekts.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_slepjukomplekts.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jRadio_slepjukomplekts.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_slepjukomplekts.setText("Slēpju komplekts");
        jRadio_slepjukomplekts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_slepjukomplektsActionPerformed(evt);
            }
        });

        jRadio_slepes.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_slepes.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_slepes.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_slepes.setText("Slēpes; ");
        jRadio_slepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_slepesActionPerformed(evt);
            }
        });

        jRadio_nujas.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_nujas.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_nujas.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_nujas.setText("Nūjas");
        jRadio_nujas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_nujasActionPerformed(evt);
            }
        });

        jRadio_slepjukivere.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_slepjukivere.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_slepjukivere.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_slepjukivere.setText("Ķivere");
        jRadio_slepjukivere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_slepjukivereActionPerformed(evt);
            }
        });

        jRadio_slepjuzabaki.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_slepjuzabaki.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_slepjuzabaki.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_slepjuzabaki.setText("Zābaki; ");
        jRadio_slepjuzabaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_slepjuzabakiActionPerformed(evt);
            }
        });

        jText_slepes_garums.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jText_slepes_garums.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_slepes_garums.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_slepes_garums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_slepes_garumsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(88, 87, 87));
        jLabel15.setText("izmērs:");

        jText_slepes_zabaki.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jText_slepes_zabaki.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_slepes_zabaki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_slepes_zabaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_slepes_zabakiActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(88, 87, 87));
        jLabel16.setText("garums:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadio_slepes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadio_slepjuzabaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_slepes_zabaki, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jText_slepes_garums)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadio_slepjukomplekts)
                            .addComponent(jRadio_slepjukivere)
                            .addComponent(jRadio_nujas))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadio_slepjukomplekts)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_slepes)
                    .addComponent(jText_slepes_garums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_slepjuzabaki)
                    .addComponent(jText_slepes_zabaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jRadio_nujas)
                .addGap(18, 18, 18)
                .addComponent(jRadio_slepjukivere)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(185, 185, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel4.setPreferredSize(new java.awt.Dimension(609, 207));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Summa bez PVN:");

        jText_sum_bez_pvn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jText_sum_bez_pvn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_sum_bez_pvn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_sum_bez_pvn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_sum_bez_pvnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Summa ar PVN:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("PVN:");

        jText_summa.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jText_summa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_summa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_summa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_summaActionPerformed(evt);
            }
        });

        jText_pvn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jText_pvn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_pvn.setText("21,0%");
        jText_pvn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_pvn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_pvnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jText_sum_bez_pvn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_pvn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jText_summa))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jText_sum_bez_pvn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText_pvn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText_summa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19))
        );

        jButton_dzest.setBackground(new java.awt.Color(255, 51, 0));
        jButton_dzest.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jButton_dzest.setForeground(new java.awt.Color(73, 73, 73));
        jButton_dzest.setText("Dzēst");
        jButton_dzest.setBorder(null);
        jButton_dzest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dzestActionPerformed(evt);
            }
        });

        jButton_aprekinat.setBackground(new java.awt.Color(0, 204, 0));
        jButton_aprekinat.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jButton_aprekinat.setForeground(new java.awt.Color(73, 73, 73));
        jButton_aprekinat.setText("Aprēķināt");
        jButton_aprekinat.setBorder(null);
        jButton_aprekinat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_aprekinatMouseClicked(evt);
            }
        });
        jButton_aprekinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aprekinatActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(185, 185, 250));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel5.setPreferredSize(new java.awt.Dimension(609, 207));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Nomas ilgums:");

        jRadio_noma1.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_noma1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_noma1.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_noma1.setText("1 stunda");
        jRadio_noma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_noma1ActionPerformed(evt);
            }
        });

        jRadio_noma2.setBackground(new java.awt.Color(185, 185, 250));
        noma_grupa.add(jRadio_noma2);
        jRadio_noma2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_noma2.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_noma2.setText("2 stundas");
        jRadio_noma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_noma2ActionPerformed(evt);
            }
        });

        jRadio_noma4.setBackground(new java.awt.Color(185, 185, 250));
        noma_grupa.add(jRadio_noma4);
        jRadio_noma4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_noma4.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_noma4.setText("4 stundas");
        jRadio_noma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_noma4ActionPerformed(evt);
            }
        });

        jRadio_nomadiena.setBackground(new java.awt.Color(185, 185, 250));
        noma_grupa.add(jRadio_nomadiena);
        jRadio_nomadiena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_nomadiena.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_nomadiena.setText("Visa diena");
        jRadio_nomadiena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_nomadienaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadio_noma1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_noma2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_noma4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_nomadiena)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_noma1)
                    .addComponent(jRadio_noma2)
                    .addComponent(jRadio_noma4)
                    .addComponent(jRadio_nomadiena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(185, 185, 250));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel6.setPreferredSize(new java.awt.Dimension(609, 207));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Pacēlājs");

        jRadio_pacelajs1.setBackground(new java.awt.Color(185, 185, 250));
        pacelajs_grupa.add(jRadio_pacelajs1);
        jRadio_pacelajs1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_pacelajs1.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_pacelajs1.setText("1 stunda");
        jRadio_pacelajs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacelajs1ActionPerformed(evt);
            }
        });

        jRadio_pacelajs2.setBackground(new java.awt.Color(185, 185, 250));
        pacelajs_grupa.add(jRadio_pacelajs2);
        jRadio_pacelajs2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_pacelajs2.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_pacelajs2.setText("2 stundas");
        jRadio_pacelajs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacelajs2ActionPerformed(evt);
            }
        });

        jRadio_pacelajs4.setBackground(new java.awt.Color(185, 185, 250));
        pacelajs_grupa.add(jRadio_pacelajs4);
        jRadio_pacelajs4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_pacelajs4.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_pacelajs4.setText("4 stundas");
        jRadio_pacelajs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacelajs4ActionPerformed(evt);
            }
        });

        jRadio_pacelajsdiena.setBackground(new java.awt.Color(185, 185, 250));
        pacelajs_grupa.add(jRadio_pacelajsdiena);
        jRadio_pacelajsdiena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_pacelajsdiena.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_pacelajsdiena.setText("Visa diena");
        jRadio_pacelajsdiena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacelajsdienaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRadio_pacelajs1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_pacelajs2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_pacelajs4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_pacelajsdiena)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_pacelajs1)
                    .addComponent(jRadio_pacelajs2)
                    .addComponent(jRadio_pacelajs4)
                    .addComponent(jRadio_pacelajsdiena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(185, 185, 250));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel8.setPreferredSize(new java.awt.Dimension(609, 207));

        jRadio_snovakomplekts.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_snovakomplekts.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jRadio_snovakomplekts.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_snovakomplekts.setText("Snovborda komplekts");
        jRadio_snovakomplekts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_snovakomplektsActionPerformed(evt);
            }
        });

        jRadio_delis.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_delis.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_delis.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_delis.setText("Dēlis; ");
        jRadio_delis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_delisActionPerformed(evt);
            }
        });

        jRadio_snovakivere.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_snovakivere.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_snovakivere.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_snovakivere.setText("Ķivere");
        jRadio_snovakivere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_snovakivereActionPerformed(evt);
            }
        });

        jRadio_snovazabaki.setBackground(new java.awt.Color(185, 185, 250));
        jRadio_snovazabaki.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRadio_snovazabaki.setForeground(new java.awt.Color(88, 87, 87));
        jRadio_snovazabaki.setText("Zābaki;");
        jRadio_snovazabaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_snovazabakiActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(88, 87, 87));
        jLabel17.setText("garums:");

        jText_delis_garums.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jText_delis_garums.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_delis_garums.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_delis_garums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_delis_garumsActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(88, 87, 87));
        jLabel18.setText("izmērs:");

        jText_snova_zabaki.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jText_snova_zabaki.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText_snova_zabaki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jText_snova_zabaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_snova_zabakiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadio_snovakomplekts)
                            .addComponent(jRadio_snovakivere))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadio_delis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadio_snovazabaki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_snova_zabaki)
                            .addComponent(jText_delis_garums))
                        .addGap(19, 19, 19))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadio_snovakomplekts)
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_delis)
                    .addComponent(jLabel17)
                    .addComponent(jText_delis_garums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_snovazabaki)
                    .addComponent(jLabel18)
                    .addComponent(jText_snova_zabaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadio_snovakivere)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTime.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jTime.setForeground(new java.awt.Color(88, 87, 87));
        jTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTime.setText("Laiks...");

        jDate.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jDate.setForeground(new java.awt.Color(88, 87, 87));
        jDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDate.setText("Datums...");

        jRekinanr.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jRekinanr.setForeground(new java.awt.Color(88, 87, 87));
        jRekinanr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRekinanr.setText("Rēķins nr...");

        jButton_notiritcheku.setBackground(new java.awt.Color(236, 85, 0));
        jButton_notiritcheku.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jButton_notiritcheku.setForeground(new java.awt.Color(73, 73, 73));
        jButton_notiritcheku.setText("Notīrīt");
        jButton_notiritcheku.setBorder(null);
        jButton_notiritcheku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_notiritchekuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton_iziet, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_notiritcheku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton_dzest, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_aprekinat, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRekinanr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_notiritcheku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_iziet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRekinanr)
                                .addGap(3, 3, 3)
                                .addComponent(jTime)
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_aprekinat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_dzest, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDate))
                        .addGap(35, 35, 35))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        //=================================izdrukā čeku=================================================
        try {
            jText_ceks.print();
        } catch (PrinterException ex) {
            Logger.getLogger(nomas_lapa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
private JFrame frame;
    private void jButton_izietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_izietActionPerformed
        
        frame = new JFrame("Iziet");
        if (JOptionPane.showConfirmDialog(frame, "Vai tiešām vēlaties pabeigt darbību?", "Brīdinājums!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton_izietActionPerformed

    private void jText_talrunisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_talrunisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_talrunisActionPerformed

    private void jText_adreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_adreseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_adreseActionPerformed

    private void jText_epastsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_epastsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_epastsActionPerformed

    private void jText_vardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_vardsActionPerformed

    }//GEN-LAST:event_jText_vardsActionPerformed

    private void jText_uzvardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_uzvardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_uzvardsActionPerformed

    private void jText_sum_bez_pvnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_sum_bez_pvnActionPerformed
    
        
        String summa_bezpvn = String.format ("$%.2f");
        if (jButton_aprekinat.isSelected())
            jText_sum_bez_pvn.setText(summa_bezpvn);
        
    }//GEN-LAST:event_jText_sum_bez_pvnActionPerformed

    private void jText_summaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_summaActionPerformed
      
        if (jButton_aprekinat.isSelected()){
            jText_summa.setText(String.valueOf(rekins));      
        }
    }//GEN-LAST:event_jText_summaActionPerformed

    private void jText_pvnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_pvnActionPerformed
   
    if (jButton_aprekinat.isSelected()){
            jText_pvn.getText();     
            String PVN = jText_pvn.getText();
    }
    }//GEN-LAST:event_jText_pvnActionPerformed

    private void jButton_dzestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dzestActionPerformed
        
        jText_pvn.setText("21,0%");
        jText_sum_bez_pvn.setText(null);
        jText_summa.setText(null);
        jText_vards.setText(null);
        jText_uzvards.setText(null);
        jText_talrunis.setText(null);
        jText_adrese.setText(null);
        jText_epasts.setText(null);
        jRadio_delis.setSelected(false);
        jRadio_noma1.setSelected(false);
        jRadio_noma2.setSelected(false);
        jRadio_noma4.setSelected(false);
        jRadio_nomadiena.setSelected(false);
        jRadio_nujas.setSelected(false);
        jRadio_pacelajs1.setSelected(false);
        jRadio_pacelajs2.setSelected(false);
        jRadio_pacelajs4.setSelected(false);
        jRadio_pacelajsdiena.setSelected(false);
        jRadio_slepes.setSelected(false);
        jRadio_slepjukivere.setSelected(false);
        jRadio_slepjukomplekts.setSelected(false);
        jRadio_slepjuzabaki.setSelected(false);
        jRadio_snovakivere.setSelected(false);
        jRadio_snovakomplekts.setSelected(false);
        jRadio_snovazabaki.setSelected(false);
        jText_slepes_garums.setText(null);
        jText_slepes_zabaki.setText(null);
        jText_snova_zabaki.setText(null);
        jText_delis_garums.setText(null);
    
        
    }//GEN-LAST:event_jButton_dzestActionPerformed

    private void jButton_aprekinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aprekinatActionPerformed



    }//GEN-LAST:event_jButton_aprekinatActionPerformed

    private void jRadio_noma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_noma2ActionPerformed
        
        if (jRadio_noma2.isSelected()){
            jRadio_noma1.setSelected(false);
            jRadio_noma4.setSelected(false);
            jRadio_nomadiena.setSelected(false);
        }
    }//GEN-LAST:event_jRadio_noma2ActionPerformed

    private void jRadio_pacelajs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacelajs2ActionPerformed
        
        if (jRadio_pacelajs2.isSelected()){
            jRadio_pacelajs1.setSelected(false);
            jRadio_pacelajs4.setSelected(false);
            jRadio_pacelajsdiena.setSelected(false);
        }
    }//GEN-LAST:event_jRadio_pacelajs2ActionPerformed

    private void jRadio_slepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_slepesActionPerformed
       
        if (jRadio_slepes.isSelected()){
            jRadio_delis.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadio_slepesActionPerformed

    private void jRadio_delisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_delisActionPerformed
        if (jRadio_delis.isSelected())
            jRadio_slepes.setSelected(false);
    }//GEN-LAST:event_jRadio_delisActionPerformed

    private void jRadio_snovakomplektsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_snovakomplektsActionPerformed
        if (jRadio_snovakomplekts.isSelected())
            jRadio_slepjukomplekts.setSelected(false);    
        
        if (jRadio_snovakomplekts.isSelected()) {
            jRadio_snovakivere.setSelected(true);
            jRadio_snovazabaki.setSelected(true);
            jRadio_delis.setSelected(true);
        }else{
            jRadio_snovakivere.setSelected(false);
            jRadio_snovazabaki.setSelected(false);
            jRadio_delis.setSelected(false);
        }
        

    }//GEN-LAST:event_jRadio_snovakomplektsActionPerformed

    private void jText_slepes_garumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_slepes_garumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_slepes_garumsActionPerformed

    private void jText_slepes_zabakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_slepes_zabakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_slepes_zabakiActionPerformed

    private void jText_delis_garumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_delis_garumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_delis_garumsActionPerformed

    private void jText_snova_zabakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_snova_zabakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_snova_zabakiActionPerformed

    private void jRadio_snovakivereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_snovakivereActionPerformed
        if (jRadio_snovakivere.isSelected());
            jRadio_slepjukivere.setSelected(false);
    }//GEN-LAST:event_jRadio_snovakivereActionPerformed

    private void jRadio_noma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_noma1ActionPerformed
        
        if (jRadio_noma1.isSelected()){
            jRadio_noma2.setSelected(false);
            jRadio_noma4.setSelected(false);
            jRadio_nomadiena.setSelected(false);
        }
    }//GEN-LAST:event_jRadio_noma1ActionPerformed

    private void jButton_aprekinatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_aprekinatMouseClicked
     /*   
        double slepes = 4;
        double slepjuzabaki = 3;
        double nujas = 1;
        double kivere = 2;
        
        double snovadelis = 4;
        double snovazabaki = 4;
        double kivere1 = 2;
        
        double noma1 = 1;
        double noma2 = 2;
        double noma4 = 3.5;
        double nomadiena = 4.5;
        
        double pacelajs1 = 13;
        double pacelajs2 = 15;
        double pacelajs4 = 17;
        double pacelajsdiena = 18;
        
        double slepesatlase = slepes + slepjuzabaki + nujas + kivere;
        double snovaatlase = snovadelis + snovazabaki + kivere1;
        double slepeskomplekts = slepesatlase - 2;
        double snovakomplekts = snovaatlase - 2;
     */   
       // (jRadio_slepjukomplekts.isSelected())
       //     jText_summa = 
       // if (jRadio_noma1.isSelected())
       // jText_summa.setText("2");
//=============================================slēpes==========================//            
int slepju_summa=0;
if (jRadio_slepjukomplekts.isSelected()){
    slepju_summa-=2; 
    rezultats += "\n -Slēpju komplekts";
}
if (jRadio_slepes.isSelected()){
    slepju_summa+=4;
    rezultats += "\n -Slēpes";
}
if (jRadio_slepjuzabaki.isSelected()){
    slepju_summa+=3;
    rezultats += "\n -Slēpju zābaki";
}
if (jRadio_nujas.isSelected()){
    slepju_summa+=1;   
    rezultats += "\n -Nūjas";
}
if (jRadio_slepjukivere.isSelected()){
    slepju_summa+=2;
    rezultats += "\n -Ķivere";
}

rekins = rekins + slepju_summa;
//==============================================snovbords======================//
int snova_summa=0;
if (jRadio_snovakomplekts.isSelected()){
    snova_summa-=1;
    rezultats += "\n -Snovborda komplekts";
}
if (jRadio_delis.isSelected()){
    snova_summa+=3;
    rezultats += "\n -Snovborda dēlis";
}
if (jRadio_snovazabaki.isSelected()){
    snova_summa+=3;      
    rezultats += "\n -Snovborda zābaki";
}
if (jRadio_snovakivere.isSelected()){
    snova_summa+=2;  
    rezultats += "\n -Ķivere";
}

rekins = rekins + snova_summa;
//============================================nomas ilgums=====================//

if (jRadio_noma1.isSelected()){
    rekins*=1;
    laiks += "\n 1 stundu";
}

else if(jRadio_noma2.isSelected()){
    rekins*=2;
    laiks += "\n 2 stundām";   
}
else if(jRadio_noma4.isSelected()){
    rekins*=3;     
    laiks += "\n 4 stundas";
}
else if(jRadio_nomadiena.isSelected()){
    rekins*=5;
    laiks += "\n visu dienu";
}
//=================================    
//==========================================pacēlājs============================


if (jRadio_pacelajs1.isSelected()){
    rekins+=13;
    pacelshana += "\n 1 stundu";
}
else if (jRadio_pacelajs2.isSelected()){
    rekins+=15;
    pacelshana += "\n 2 stundām";
}
else if (jRadio_pacelajs4.isSelected()){
    rekins+=17;
    pacelshana += "\n 4 stundām";
}
else if (jRadio_pacelajsdiena.isSelected()){
    rekins+=18;
    pacelshana += "\n visai dienai";
}




//====================Laiks-----------------------------------------------------
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        jTime.setText(tTime.format(timer.getTime()));
//===================Datums-----------------------------------------------------      
        SimpleDateFormat Tdate = new SimpleDateFormat("dd MMM yyyy");
        jDate.setText(Tdate.format(timer.getTime()));
        
//===================Rēķina numurs----------------------------------------------
        int num1;
        String q1 ="";
        num1 = 1325 + (int) (Math.random()*4238);
        q1 += num1 + 1325;
        jRekinanr.setText(q1);
        
//==============================================================================        

jText_ceks.append("\tNomas reģistrācijas čeks\n\n"+
        "Rēķina nr:\t"+ String.valueOf(q1) + "\n"+
        "Datums: \t"+ String.valueOf(Tdate.format(timer.getTime())) + "\n"+      
        "Laiks: \t"+ String.valueOf(tTime.format(timer.getTime())) + "\n"+
        "Nomas dati: \t" + jText_vards.getText() + " " + jText_uzvards.getText() +" "+ jText_adrese.getText() + "\n"+
        "Tālrunis: \t" + jText_talrunis.getText() + "\n" +
        "E-pasts: \t" + jText_epasts.getText() +
    "\n----------------------------------------------------\n" +        
        "Summa par inventāra nomu:" + String.valueOf(rekins) + "\n\n" +
        "Jūsu izvēlētais inventārs: \t\t" + rezultats + "\n"+
    "\n----------------------------------------------------\n" +                
        "Nomāts uz:" + laiks +
    "\n----------------------------------------------------\n" +                      
        "Ar pacēlāju uz: \t" + pacelshana +
    "\n================================\n" 
            + "\n\n\tPaldies par pirkumu"
        
);
   





       


    }//GEN-LAST:event_jButton_aprekinatMouseClicked

    private void jRadio_noma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_noma4ActionPerformed

        if (jRadio_noma4.isSelected())
            jRadio_noma1.setSelected(false);
            jRadio_noma2.setSelected(false);
            jRadio_nomadiena.setSelected(false);
    }//GEN-LAST:event_jRadio_noma4ActionPerformed

    private void jRadio_nomadienaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_nomadienaActionPerformed
        
        if (jRadio_nomadiena.isSelected())
            jRadio_noma2.setSelected(false);
            jRadio_noma4.setSelected(false);
            jRadio_noma1.setSelected(false);
    }//GEN-LAST:event_jRadio_nomadienaActionPerformed

    private void jRadio_pacelajs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacelajs1ActionPerformed
       
        if (jRadio_pacelajs1.isSelected())
            jRadio_pacelajs2.setSelected(false);
            jRadio_pacelajs4.setSelected(false);
            jRadio_pacelajsdiena.setSelected(false);
    }//GEN-LAST:event_jRadio_pacelajs1ActionPerformed

    private void jRadio_pacelajs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacelajs4ActionPerformed
       
        if (jRadio_pacelajs4.isSelected())
            jRadio_pacelajs1.setSelected(false);
            jRadio_pacelajs2.setSelected(false);
            jRadio_pacelajsdiena.setSelected(false);  
    }//GEN-LAST:event_jRadio_pacelajs4ActionPerformed

    private void jRadio_pacelajsdienaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacelajsdienaActionPerformed
        
        if (jRadio_pacelajsdiena.isSelected())
            jRadio_pacelajs2.setSelected(false);
            jRadio_pacelajs4.setSelected(false);
            jRadio_pacelajs1.setSelected(false);
        
    }//GEN-LAST:event_jRadio_pacelajsdienaActionPerformed

    private void jRadio_slepjukomplektsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_slepjukomplektsActionPerformed
     if (jRadio_slepjukomplekts.isSelected()){
            jRadio_snovakomplekts.setSelected(false);      
        }
        
        if (jRadio_slepjukomplekts.isSelected()) {
            jRadio_slepes.setSelected(true);
            jRadio_slepjukivere.setSelected(true);
            jRadio_slepjuzabaki.setSelected(true);
            jRadio_nujas.setSelected(true);
        }else{
            jRadio_slepes.setSelected(false);
            jRadio_slepjukivere.setSelected(false);
            jRadio_slepjuzabaki.setSelected(false);
            jRadio_nujas.setSelected(false);
        }
   

            
    }//GEN-LAST:event_jRadio_slepjukomplektsActionPerformed

    private void jButton_notiritchekuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_notiritchekuActionPerformed

        jText_ceks.setText(null);

    }//GEN-LAST:event_jButton_notiritchekuActionPerformed

    private void jRadio_slepjuzabakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_slepjuzabakiActionPerformed
        if (jRadio_slepjuzabaki.isSelected());
            jRadio_snovazabaki.setSelected(false);
    }//GEN-LAST:event_jRadio_slepjuzabakiActionPerformed

    private void jRadio_snovazabakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_snovazabakiActionPerformed
        if (jRadio_snovazabaki.isSelected());
            jRadio_slepjuzabaki.setSelected(false);
    }//GEN-LAST:event_jRadio_snovazabakiActionPerformed

    private void jRadio_nujasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_nujasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_nujasActionPerformed

    private void jRadio_slepjukivereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_slepjukivereActionPerformed
        if (jRadio_slepjukivere.isSelected());
            jRadio_snovakivere.setSelected(false);
    }//GEN-LAST:event_jRadio_slepjukivereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nomas_lapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nomas_lapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nomas_lapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nomas_lapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nomas_lapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton_aprekinat;
    javax.swing.JButton jButton_dzest;
    javax.swing.JButton jButton_iziet;
    javax.swing.JButton jButton_notiritcheku;
    javax.swing.JLabel jDate;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel18;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel8;
    javax.swing.JRadioButton jRadio_delis;
    javax.swing.JRadioButton jRadio_noma1;
    javax.swing.JRadioButton jRadio_noma2;
    javax.swing.JRadioButton jRadio_noma4;
    javax.swing.JRadioButton jRadio_nomadiena;
    javax.swing.JRadioButton jRadio_nujas;
    javax.swing.JRadioButton jRadio_pacelajs1;
    javax.swing.JRadioButton jRadio_pacelajs2;
    javax.swing.JRadioButton jRadio_pacelajs4;
    javax.swing.JRadioButton jRadio_pacelajsdiena;
    javax.swing.JRadioButton jRadio_slepes;
    javax.swing.JRadioButton jRadio_slepjukivere;
    javax.swing.JRadioButton jRadio_slepjukomplekts;
    javax.swing.JRadioButton jRadio_slepjuzabaki;
    javax.swing.JRadioButton jRadio_snovakivere;
    javax.swing.JRadioButton jRadio_snovakomplekts;
    javax.swing.JRadioButton jRadio_snovazabaki;
    javax.swing.JLabel jRekinanr;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField jText_adrese;
    javax.swing.JTextArea jText_ceks;
    javax.swing.JTextField jText_delis_garums;
    javax.swing.JTextField jText_epasts;
    javax.swing.JTextField jText_pvn;
    javax.swing.JTextField jText_slepes_garums;
    javax.swing.JTextField jText_slepes_zabaki;
    javax.swing.JTextField jText_snova_zabaki;
    javax.swing.JTextField jText_sum_bez_pvn;
    javax.swing.JTextField jText_summa;
    javax.swing.JTextField jText_talrunis;
    javax.swing.JTextField jText_uzvards;
    javax.swing.JTextField jText_vards;
    javax.swing.JLabel jTime;
    javax.swing.ButtonGroup noma_grupa;
    javax.swing.ButtonGroup pacelajs_grupa;
    // End of variables declaration//GEN-END:variables
}
